const MOVIES_SERVER_ADDRESS = 'https://api.nomoreparties.co/beatfilm-movies';
const MAIN_SERVER_ADDRESS = 'https://api.slammovies.nomoreparties.sbs';
const NAME_REGEX = /^[a-zA-Zа-яА-Я\s-]+$/;
const SHORT_MOVIE_DURATION = 40;
const NUMBER_OF_MOVIES_DESKTOP = 12;
const NUMBER_OF_MOVIES_TABLET = 8;
const NUMBER_OF_MOVIES_MOBILE = 5;
const MOVIES_TO_ADD_DESKTOP = 3;
const MOVIES_TO_ADD_MOBILE = 2;
const SCREEN_WIDTH_DESKTOP = 1200;
const SCREEN_WIDTH_TABLET = 768;
export {
  MOVIES_SERVER_ADDRESS,
  MAIN_SERVER_ADDRESS,
  NAME_REGEX,
  SHORT_MOVIE_DURATION,
  NUMBER_OF_MOVIES_DESKTOP,
  NUMBER_OF_MOVIES_TABLET,
  NUMBER_OF_MOVIES_MOBILE,
  MOVIES_TO_ADD_DESKTOP,
  MOVIES_TO_ADD_MOBILE,
  SCREEN_WIDTH_DESKTOP,
  SCREEN_WIDTH_TABLET,
};
